package utils

func Languages() map[string]string {
	return languageMap
}

func LanguageByCode(code string) string {
	return languageMap[code]
}

func ValidLanguage(code string) bool {
	_, valid := languageMap[code]
	return valid
}

var languageMap = map[string]string{
	"aa":           "Afar",
	"ab":           "Abkhazian",
	"ak":           "Akan",
	"am":           "Amharic",
	"an":           "Aragonese",
	"ar":           "Arabic",
	"ary":          "Moroccan Arabic",
	"as":           "Assamese",
	"az":           "Azerbaijani",
	"ba":           "Bashkir",
	"be":           "Belarusian",
	"be-x-old":     "Taraškievica",
	"bg":           "Bulgarian",
	"bn":           "Bengali",
	"bo":           "Tibetan",
	"br":           "Breton",
	"bs":           "Bosnian",
	"ca":           "Catalan",
	"ceb":          "Cebuano",
	"ch":           "Chamorro",
	"co":           "Corsican",
	"cr":           "Cree",
	"cs":           "Czech",
	"cy":           "Welsh",
	"da":           "Dansk",
	"de":           "Deutsch",
	"diq":          "Zazaki",
	"dv":           "Divehi",
	"dz":           "Dzongkha",
	"el":           "Greek",
	"en":           "English",
	"eo":           "Esperanto",
	"es":           "Español",
	"et":           "Estonian",
	"eu":           "Basque",
	"fa":           "Persian",
	"fi":           "Finnish",
	"fo":           "Faroese",
	"fr":           "French",
	"frp":          "Franco-Provençal",
	"fy":           "West Frisian",
	"ga":           "Irish",
	"gl":           "Galician",
	"gn":           "Guarani",
	"he":           "Hebrew",
	"hi":           "Hindi",
	"hr":           "Croatian",
	"ht":           "Haitian",
	"hu":           "Hungarian",
	"hy":           "Armenian",
	"id":           "Indonesian",
	"ig":           "Igbo",
	"ilo":          "Ilokano",
	"is":           "Icelandic",
	"it":           "Italiano",
	"ja":           "Japanese",
	"jbo":          "Lojban",
	"jv":           "Javanese",
	"ka":           "Georgian",
	"kab":          "Kabyle",
	"kg":           "Kongo",
	"ki":           "Kikuyu",
	"kk":           "Kazakh",
	"km":           "Khmer",
	"kn":           "Kannada",
	"ko":           "Korean",
	"kr":           "Kanuri",
	"ku":           "Kurdish (Kurmanji)",
	"kw":           "Cornish",
	"ky":           "Kirghiz: Кыргызча",
	"la":           "Latin",
	"lb":           "Luxembourgish",
	"ln":           "Lingala",
	"lo":           "Lao",
	"lt":           "Lithuanian",
	"ltg":          "Latgalian",
	"lv":           "Latvian",
	"mai":          "Maithili",
	"mg":           "Malagasy",
	"mi":           "Maori",
	"mk":           "Macedonian",
	"ml":           "Malayalam",
	"mn":           "Mongolian",
	"mr":           "Marathi",
	"ms":           "Malay",
	"mt":           "Maltese",
	"my":           "Burmese",
	"myv":          "Erzya",
	"ne":           "Nepali",
	"nl":           "Dutch",
	"nn":           "Norwegian (Nynorsk)",
	"no":           "Norwegian (Bokmål)",
	"nso":          "Northern Sotho",
	"ny":           "Chichewa",
	"oc":           "Occitan",
	"om":           "Oromo",
	"or":           "Oriya",
	"pa":           "Eastern Punjabi",
	"pap":          "Papiamentu",
	"pl":           "Polish",
	"pms":          "Piedmontese",
	"pt":           "Portuguesa",
	"qu":           "Quechua",
	"ro":           "Romanian",
	"ru":           "Russian",
	"rw":           "Kinyarwanda",
	"se":           "Northern Sami",
	"sh":           "Serbo-Croatian",
	"si":           "Sinhalese",
	"sk":           "Slovak",
	"sl":           "Slovenian",
	"sq":           "Albanian",
	"srd":          "Sardinian",
	"sr":           "Serbian",
	"su":           "Sundanese",
	"sv":           "Svenska",
	"sw":           "Swahili",
	"szl":          "Silesian",
	"ta":           "Tamil",
	"te":           "Telugu",
	"tg":           "Tajik",
	"th":           "Thai",
	"tk":           "Turkmen",
	"tl":           "Tagalog",
	"tn":           "Tswana",
	"tr":           "Turkish",
	"tt":           "Tatar",
	"tw":           "Twi",
	"uk":           "Ukrainian",
	"ur":           "Urdu",
	"uz":           "Uzbek",
	"ve":           "Venda",
	"vi":           "Vietnamese",
	"wa":           "Walloon",
	"wo":           "Wolof",
	"xh":           "Xhosa",
	"yi":           "Yiddish",
	"yo":           "Yoruba",
	"zh":           "Chinese",
	"zu":           "Zulu",
}
